### ISSUE TITLE
[Extrachat] Server stopped authenticating numerous accounts

### ISSUE THREAD

**Issue by telamarna** [lojewalo/plugin-issues#101]
All the extrachat users all were unable to connect 
to extrachat. We're all stuck with the same issue of authenticating. Images attached. The disconnect started on 2/6/24.
<img width="97" alt="ffxiv_dx11_7b4Gknp3iI" src="https://github.com/lojewalo/plugin-issues/assets/23287394/f3f7f4ee-3a10-44e3-b591-9f52fb0501b1">
<img width="827" alt="ffxiv_dx11_1EPecrg4Ba" src="https://github.com/lojewalo/plugin-issues/assets/23287394/2ec0eaa7-bbf3-4f4d-8d49-4ed14a7589d5">

**Comment by lojewalo** [comment]
Fixed now, thanks for the report

**Comment by telamarna** [comment]
> Fixed now, thanks for the report

may need to reopen, same issue as this before as of newest patch

**Comment by telamarna** [comment]
![image](https://github.com/anna-is-cute/plugin-issues/assets/23287394/85d98c61-2792-4652-94cc-8a9c8d508fca)
