### ISSUE TITLE
ExtraChat stuck reconnecting even after resetting keys

### ISSUE THREAD

**Issue by 264-bit** [lojewalo/plugin-issues#89]
I'm using Extrachat and it's stuck in a reconnection loop for me.  I've reset my keys twice by deleting ExtraChat.json in dalamud's pluginConfigs, and the same issue occurs as soon as I register new keys.  Is there any way to fully reset my account, or any other way to fix this?

Error log from Dalamud: `{"When":"2023-09-24T19:24:34.7926309-07:00","Info":"System.Exception: Exception of type 'System.Exception' was thrown.\r\n   at ExtraChat.Ext.ReceiveMessage(ClientWebSocket client) in /work/repo/client/ExtraChat/Ext.cs:line 28\r\n   at ExtraChat.Client.Loop() in /work/repo/client/ExtraChat/Client.cs:line 589\r\n   at ExtraChat.Client.<StartLoop>b__43_0() in /work/repo/client/ExtraChat/Client.cs:line 99","Context":"[ExtraChat] Error in client loop"}`
I tried this on an alt character, and it is working fine.  It is only my main character which has this issue.

**Comment by 264-bit** [comment]
Gave this a try with the 6.5 update, also tried resetting keys/reregistering again.  Still running into the same issue.
Would really appreciate help with this.

**Comment by Maxunit** [comment]
This is getting worse and worse. Pretty much everyone from a bigger EC Shell I am in is stuck in this reconnect loop now. One after another fell victim to it within around 48 hours.

**Comment by Otaku-2** [comment]
I can say at least for myself and quite a few others that ExtraChat has started entering a connection loop within the past week, spamming chat with "Connected to ExtraChat" to "Disconnected from ExtraChat. Trying to reconnect." back-to-back, and never seemingly getting a connection. This happens regardless of stop and restarting, reinstalling, or deleting and remaking the account.

For some people it works fine on secondary characters, though, so the problem most likely isn't client-side, but I wouldn't know any more than that.

**Comment by lojewalo** [comment]
None of you are providing any useful information. I need logs and character names, and even then, I can't make this issue happen. I'll look at it for a few minutes if I get actual useful info.

**Comment by lojewalo** [comment]
If you're all having the same issue, which I can't verify, this might fix it: https://github.com/goatcorp/DalamudPluginsD17/pull/2898

**Comment by 264-bit** [comment]
Thanks for the update!  I am now able to reconnect with 1.3.5.
I can't talk in any ECLs anymore, and they are all showing up as ???, but that is another issue.
