### ISSUE TITLE
[xivpf] How to contribute?

### ISSUE THREAD

**Issue by czyba** [lojewalo/plugin-issues#94]
Cheers,

I've become a fan of xivpf, since DC travel became a thing.

I'd like to contribute to xivpf. I did find the repository, but I could not find a readme, or a way to create Pull Requests. How would I go about contributing to the software and helping out?

Kind Regards
Chris

**Comment by lojewalo** [comment]
If you want to submit code, you can email me a patchset. Note that I'm fairly picky about contributions, though. You can find my email in the commits or at [my site](https://anna.lgbt).
